### ISSUE TITLE
userdata strings are hard to compare

### ISSUE THREAD

**Issue by Jragon** [hughesjs/Folder-Compare#1]
It's difficult to spot the difference in a userdata string.

Proposed solution: when the user clicks on userdata line it should show the aliases in that userdata string

**Comment by Jragon** [comment]
Jragon/Folder-Compare/fe17f8320456d6926f4ac0e5f6b1b42445b8e751

I couldn't get the box to show up

**Comment by hughesjs** [comment]
You can use the `.BringToFront()` method of the control to fix that

**Comment by Jragon** [comment]
programming is ez
